site_name: loadPoint's Dynamic Note for 2024
site_url: https://loadpoint.github.io/
theme:
  name: material
  features:
    - navigation.tabs
nav:
  - Welcome Page: 'index.md'
  - CS-150:
    - DSA-70:
      - '概述': 'CS-150/DSA-70/dsa.md'
      - '树状数据结构': 'CS-150/DSA-70/dsa-tree.md'
    - OS-30:
      - '概述': 'CS-150/OS-30/os.md'
    - PCC-30:
      - '概述': 'CS-150/PCC-30/pcc.md'
